params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: transformer
    space:
      continuous:

    transformer:
      #input_split: [77,77,77,77,77,77,77,77]
      input_split: [42,42,42,42]
      seq_pool: True
      embedding_dim: 256
      num_layers: 3
      num_heads: 2
      mlp_ratio: 2.0
      dropout: 0.0
      attention_dropout: 0.0
      stochastic_depth: 0.0
      positional_embedding: none

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:ShadowHandAsymmTransformer,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0 #0.01
    normalize_advantage: True
    gamma: 0.998
    tau: 0.95
    learning_rate: 3e-4
    #lr_schedule: None
    lr_schedule: linear
    #lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.016
    score_to_win: 100000
    max_epochs: ${resolve_default:5000,${....max_iterations}}
    save_best_after: 500
    save_frequency: 500
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 16384
    mini_epochs: 4
    critic_coef: 4
    clip_value: True
    seq_length: 4
    use_experimental_cv: False
    bound_loss_type: regularisation #bound, None
    bounds_loss_coef: 0.0002

    central_value_config:
      minibatch_size: 16384
      mini_epochs: 8
      learning_rate: 5e-4
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.016
      clip_value: True
      normalize_input: True
      truncate_grads: True

      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [512, 512, 256, 128]
          activation: elu
          d2rl: False
          initializer:
            name: default
          regularizer:
            name: None

    player:
      #render: True
      deterministic: True
      games_num: 1000000
      print_stats: False